[book]
authors = ["The Rand Project Developers"]
title = "The Rust Rand Book"
description = "Extended documentation for Rust's Rand lib"
language = "en"

[rust]
edition = "2024"

[output.html.playground]
editable = true

# [output.linkcheck]
# NOTE: this requires https://github.com/Michael-F-Bryan/mdbook-linkcheck
