[book]
authors = ["The Rand Project Developers"]
src = "src"
title = "The Rust Rand Book"
description = "Extended documentation for Rust's Rand lib"

[output.html.playgen]
editable = true

[output.linkcheck]
# NOTE: this requires https://github.com/Michael-F-Bryan/mdbook-linkcheck
